### PR TITLE
Modified vip fqrn parameters

### PR DESCRIPTION
**Pull request by leefaisonr**

### CODE REVIEW

**Comment by acozine** [comment]
Current failure (from the figgy role) is:
```
TASK [common : common | install dust] ******************************************
  fatal: [instance]: FAILED! => {"changed": false, "msg": "Failure downloading https://github.com/bootandy/dust/releases/download//v0.8.3/du-dust_0.8.3_amd64.deb, HTTP Error 503: Egress is over the account limit."}
```
Should we add `dust` to the items we mirror locally?

**Comment by hackartisan** [comment]
> Should we add `dust` to the items we mirror locally?

Maybe keep an eye on it to see if it keeps happening?

**Review by hackartisan — APPROVED** [review]

**Review by kayiwa — COMMENTED** [review]
add `ansible.builtin.action` to https://github.com/pulibrary/princeton_ansible/blob/i2861_vips_fqrn/roles/vips/handlers/main.yml#L3

**Comment by kayiwa** [comment]
> Current failure (from the figgy role) is:
> 
> ```
> TASK [common : common | install dust] ******************************************
>   fatal: [instance]: FAILED! => {"changed": false, "msg": "Failure downloading https://github.com/bootandy/dust/releases/download//v0.8.3/du-dust_0.8.3_amd64.deb, HTTP Error 503: Egress is over the account limit."}
> ```
> 
> Should we add `dust` to the items we mirror locally?

Github will always be more reliable than anything we do, no? ;-)

**Pull request merged**
