### PR TITLE
Encrypting the private keys for oaworkflow

### PR DESCRIPTION
**Pull request by jrgriffiniii**
Resolves https://github.com/pulibrary/oawaiver/issues/123

### CODE REVIEW

**Review by kayiwa — APPROVED** [review]
OK! Thanks @jrgriffiniii

**Comment by jrgriffiniii** [comment]
I apologize, I am going to add the PFX chain with this.

**Comment by kayiwa** [comment]
we don't need the *.pfx file @jrgriffiniii

**Comment by jrgriffiniii** [comment]
I apologize, I also included a dated key. I have updated this in the most recent commit.

**Pull request merged**
