### PR TITLE
Updating NodeJS to 12.x LTS releases for the pulibrary.figgy Role

### LINKED ISSUE #1154: upgrade node version on figgy machines
At least 10.16. Higher?

### PR DESCRIPTION
**Pull request by jrgriffiniii**
Resolves #1154

### CODE REVIEW

**Comment by jrgriffiniii** [comment]
The test failure on GitHub Actions was due to the `pulibrary.ruby` Role: https://github.com/pulibrary/princeton_ansible/pull/1303/checks?check_run_id=468036206

**Comment by jrgriffiniii** [comment]
While testing this against the `figgy-staging2` server environment, I receive the following error:

```
TASK [pulibrary.common : update python's crypto libs] *******************************************
fatal: [figgy-staging2.princeton.edu]: FAILED! => {"changed": false, "msg": "Unable to find any of pip2, pip to use.  pip needs to be installed."}

PLAY RECAP **************************************************************************************
figgy-staging2.princeton.edu : ok=4    changed=2    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

I doubt that this was related to any changes which were introduced by the commits in this PR.

**Comment by jrgriffiniii** [comment]
`roles/pulibrary.nodejs` is specified in the `figgy_production` Playbook: https://github.com/pulibrary/princeton_ansible/blob/master/playbooks/figgy_production.yml#L20 but is not present in https://github.com/pulibrary/princeton_ansible/blob/master/playbooks/figgy_staging.yml#L8

**Comment by jrgriffiniii** [comment]
I'm not certain how to approach this further, as when one installs version 12.x on a server with an older release of NodeJS installed, `apt-get update` needs to be run, followed by the removal of the older release. Perhaps porting some of what I had in https://github.com/pulibrary/princeton_ansible/pull/946/files#diff-76f5a797fe1dcaebb928b3cd3b12ba38R78 might be an approach.

**Comment by jrgriffiniii** [comment]
This has been tested against `figgy-staging2`, which previously had release 8.17.0 installed:
```
deploy@figgy-staging2:~$ node --version
v8.17.0
```

this was updated to:

```
pulsys@figgy-staging2:~$ node --version
v12.16.1
```

**Comment by jrgriffiniii** [comment]
I've fixed the linting error and have provided a test for this extended behavior with https://github.com/pulibrary/princeton_ansible/pull/1303/commits/b3be90a7c5a2679088597b20ec43ea42c8821f75

**Comment by jrgriffiniii** [comment]
It was necessary to resolve https://github.com/yarnpkg/yarn/issues/7866#issue-558663837 on figgy-staging1 while testing this.

**Comment by tpendragon** [comment]
@jrgriffiniii I assume this is ready? It looks good to me.

**Pull request merged**
