### PR TITLE
[prancible] install falcon-sensor

### PR DESCRIPTION
**Pull request by kayiwa**
Install falcon-sensor on RHEL

### CODE REVIEW

**Comment by acozine** [comment]
I learned today that there is a crowdstrike collection, maybe they have a module that would do the install for us? That might also take care of the uninstall issues we've been seeing @kayiwa

**Comment by acozine** [comment]
https://galaxy.ansible.com/ui/repo/published/crowdstrike/crowdstrike/ and https://galaxy.ansible.com/ui/repo/published/crowdstrike/falcon/

**Comment by VickieKarasic** [comment]
Reviewed in Ansible Open Hours; this PR is superseded by #5217.

**Comment by kayiwa** [comment]
closed by #5474

**Pull request closed without merging**
