### PR TITLE
Redirects the CheckMK sites

### LINKED ISSUE #4809: [CheckMK] Traffic to checkMK site should go to the full site URL
Right now, if you open a browser to https://pulcheck-staging.princeton.edu (from on the VPN), you get the standard Apache default page. This is because CheckMK defines a "site" after the main URL. The correct URL for our staging site is https://pulcheck-staging.princeton.edu/pulmonitor/.

Modify the nginx configuration file for pulcheck-staging to send all traffic to the correct URL.

### PR DESCRIPTION
**Pull request by leefaisonr**
closes #4809

### CODE REVIEW

**Comment by acozine** [comment]
Per @kayiwa we should copy the pattern from the [datacommons config](https://github.com/pulibrary/princeton_ansible/blob/9613013ddf9d2e0c62ba216286370e0af7b236e4/roles/nginxplus/files/conf/http/datacommons.conf).

**Comment by acozine** [comment]
Tested today - the redirection works, but it seems to break our authentication settings - I get a popup window asking for a Username and Password instead of the SSO auth.

**Comment by acozine** [comment]
Updated the config and deployed to both LBs today. Worked on my machine; awaiting confirmation from others.

**Comment by acozine** [comment]
I did not deploy the production changes today, but they *should* work the same as staging.

**Comment by acozine** [comment]
Tested today, and both staging and production redirect correctly with this config.

**Review by jrgriffiniii — APPROVED** [review]

**Review by carolyncole — APPROVED** [review]

**Pull request merged**
