### PR TITLE
[ORANGELIGHT] Update nodejs on staging and qa

### PR DESCRIPTION
**Pull request by sandbergja**

### CODE REVIEW

**Comment by christinach** [comment]
@kayiwa @acozine why the molecule tests dont run?

**Comment by acozine** [comment]
I think we had a lot of PRs getting merged today, so the test system was backed up. 

To fix the failure that happened when the tests finally did run, we can try editing [.ansible-lint for this role](https://github.com/pulibrary/princeton_ansible/blob/ae5054049b071c717c37693c41ca9b75603f8fe8/roles/capistrano/.ansible-lint) and adding `- role-name` to it. But that might not fix the issue, see [this bug report. ](https://github.com/ansible/ansible-compat/issues/78).

**Comment by sandbergja** [comment]
Just rebased against main and force-pushed.

**Comment by acozine** [comment]
Looks good, thanks @sandbergja.

**Pull request merged**
