### PR TITLE
Automatically pull ansible-vault from lastpass

### PR DESCRIPTION
**Pull request by tpendragon**

### CODE REVIEW

**Comment by escowles** [comment]
I wasn't able to get this working.  When I tried to decrypt a vault file, I got the error:

```
 [WARNING]: Error in vault password file loading (default): Invalid vault password was provided from script
(/Users/escowles/.rbenv/shims/lastpass-ansible)
```

When I tried to go into LastPass to check the shared vault password, it said it was a shared password and so I could not view/copy it (only fill it in a form, I guess?)

**Comment by tpendragon** [comment]
@escowles Maybe it's a permission thing, one sec.

**Comment by kayiwa** [comment]
yes install a gem globally is cool!

**Comment by tampakis** [comment]
Works great! I just rebased against master

**Pull request merged**
