### PR TITLE
Add mount for lib-gissystem

### LINKED ISSUE #26: Create mount on plum for geo data
Create an nfs mount to lib-gissystem:gbl to use a source for initial ingest of scanned maps and vector datasets. See Also: https://github.com/pulibrary/plum/issues/1216

### PR DESCRIPTION
**Pull request by eliotjordan**
Closes #26

### CODE REVIEW

**Comment by eliotjordan** [comment]
@kayiwa Does this look like the right way to add a read-only nfs mount to plum and the plum worker boxes? There is no password, and I long ago discovered that I had to use the ip instead of the FQDN to get this to work. Windows 😞 .

**Comment by kayiwa** [comment]
said differently... while the OS would boot without problems if it doesn't resolve an additional

```
mount -t nfs
```
step will be required every time there will be a power on, just to be sure.

**Comment by eliotjordan** [comment]
@kayiwa I think I addressed your concerns with this. If not, let me know. FWIW, I don't expect that this will be a permanent change to the configuration. We only need to mount this share while we import our existing collection of geo objects.

**Comment by eliotjordan** [comment]
@kayiwa ^ I meant to say that i force-pushed some changes to this commit.

**Comment by kayiwa** [comment]
apologies for this. I could have sworn I merged it. :-(

**Pull request merged**
