### PR TITLE
update python, ansible and molecule

### PR DESCRIPTION
**Pull request by kayiwa**
this is a security update updating our version of ansible to 4.2.0
we are also updating our python version to 3.10.x

### CODE REVIEW

**Review by hackartisan — CHANGES_REQUESTED** [review]
How do I make this work? I did:
* asdf install
* pip install --user pipenv
* pipenv sync
-> No such command in 3.10.0 of python

**Comment by acozine** [comment]
@hackartisan if you do `pip3 install --user pipenv` and then try again, does that fix it?

**Review by jrgriffiniii — APPROVED** [review]
Thank you very much @kayiwa! This is indeed working within my local development environment:

```bash
✔ Successfully created virtual environment!
Virtualenv location: /Users/jrg5/.local/share/virtualenvs/princeton_ansible-29XelqEd
Installing dependencies from Pipfile.lock (7650b3)...
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 59/59 — 00:03:13
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
All dependencies are now up-to-date!
~/.../princeton_ansible security_ansible_upgrade ❯ /Users/jrg5/.asdf/installs/python/3.10.0/bin/pipenv shell
Launching subshell in virtual environment...
 . /Users/jrg5/.local/share/virtualenvs/princeton_ansible-29XelqEd/bin/activate
~/.../princeton_ansible security_ansible_upgrade ❯  . /Users/jrg5/.local/share/virtualenvs/princeton_ansible-2
9XelqEd/bin/activate
~/.../princeton_ansible security_ansible_upgrade ❯
```

**Comment by carolyncole** [comment]
It worked for me.  I exited the pipenv shell I had open.  Changed to the branch. Then ran `pipenv sync` had to run the `pipenv --rm` and `pipenv sync` again.

**Comment by christinach** [comment]
It worked for me. Thank you!

**Comment by acozine** [comment]
@kayiwa I'd vote to put the changes to the common role and to the test suite into a different PR or PRs, and focus this one on updating our virtual environment for running Ansible playbooks.

**Comment by hackartisan** [comment]
Okay I got it working. I had a file stuck locked to python 3.9.10 even after I did the python upgrade:

```
$ cat /Users/aheadley/.asdf/shims/pipenv                                                                                          
#!/usr/bin/env bash                                                                                                                                                                   
# asdf-plugin: python                                                                                                                                                                 
# asdf-plugin-version: 3.9.0                                                                                                                                                          
exec /Users/aheadley/.asdf/bin/private/asdf-exec python bin/pipenv "$@" 
```

I deleted that and uninstalled / reinstalled python (via asdf), did asdf reshim, updated pip, cleared pip cache, uninstalled / reinstalled pipenv.

**Pull request merged**
