### PR TITLE
coalesce orangelight playbooks into one

### PR DESCRIPTION
**Pull request by kayiwa**

### CODE REVIEW

**Review by christinach — CHANGES_REQUESTED** [review]
@kayiwa do we need to include role: 'postgresql' in https://github.com/pulibrary/princeton_ansible/blob/786d33b0eebf466f1db9f1c5921aaddeb8134d0e/roles/orangelight/meta/main.yml#L16 ?

**Comment by sandbergja** [comment]
I think that #3273 took care of this

**Comment by kayiwa** [comment]
heya @christinach blacklight --> rails_app (which has postgresql) dependency. Could you please unblock?

**Review by christinach — APPROVED** [review]

**Comment by acozine** [comment]
Branch rebased. @sandbergja's PR consolidated the playbooks. Keeping the modified Slack message.

**Comment by sandbergja** [comment]
Thanks for rebasing, @acozine! To give credit where it is due, it was @maxkadel's PR that consolidated them. :-)

**Comment by acozine** [comment]
Ah, I didn't do my research! Thanks @maxkadel for the PR.

**Pull request merged**
