### PR TITLE
Create playbook for checkmk agent

### PR DESCRIPTION
**Pull request by leefaisonr**
To run this, you need to install the CheckMk collection: https://galaxy.ansible.com/ui/repo/published/checkmk/general/

### CODE REVIEW

**Comment by acozine** [comment]
Related to #4648

**Comment by jrgriffiniii** [comment]
Please note that I was able to install this successfully with the following:

```bash
$ bin/setup
$ pipenv shell
$ pipenv sync
$ ansible-galaxy install checkmk
```

**Comment by jrgriffiniii** [comment]
The following error occurred:

```bash
fatal: [pdc-describe-staging2.princeton.edu]: FAILED! => {"attempts": 3, "changed": false, "dest": "/tmp/check-mk-agent_2.2.0p19-vanilla.deb", "elapsed": 0, "msg": "Request failed", "response": "HTTP Error 404: Not Found", "status_code": 404, "url": "https://pulcheck-staging.princeton.edu:443/pulmonitor/check_mk/agents/check-mk-agent_2.2.0p19-1_all.deb"}
```

**Comment by jrgriffiniii** [comment]
API authorization is now failing:

```bash
TASK [checkmk.general.agent : Fetch fresh monitoring data from host.] *****************************************************************************************************************
FAILED - RETRYING: [pdc-describe-staging2.princeton.edu -> localhost]: Fetch fresh monitoring data from host. (3 retries left).
FAILED - RETRYING: [pdc-describe-staging2.princeton.edu -> localhost]: Fetch fresh monitoring data from host. (2 retries left).
FAILED - RETRYING: [pdc-describe-staging2.princeton.edu -> localhost]: Fetch fresh monitoring data from host. (1 retries left).
fatal: [pdc-describe-staging2.princeton.edu -> localhost]: FAILED! => {"attempts": 3, "changed": false, "msg": "401 - Error calling API Details: b'{\"title\": \"Unauthorized\", \"stat
us\": 401, \"detail\": \"Wrong credentials (Bearer header)\"}'"}
```

**Comment by jrgriffiniii** [comment]
This seems to be the offending line: https://github.com/Checkmk/ansible-collection-checkmk.general/blob/main/roles/agent/tasks/main.yml#L23C1-L23C49

**Comment by acozine** [comment]
I found two resources that seem to address our issue:
https://forum.checkmk.com/t/registration-to-my-checkmk-server-fails-with-401-unauthorized/33829/3
https://forum.checkmk.com/t/issue-running-cmk-agent-ctl-exe-register-with-error-request-failed-with-code-401-unauthorized/31735/2
If I'm following the information there, we need to connect to the Agent Receiver - it is running:
```
OMD[pulmonitor]:~$ omd config show | grep RECEIVER
AGENT_RECEIVER: on
AGENT_RECEIVER_PORT: 8000
```
Port 8000 is not open - I will try opening it and see where that gets us.

**Comment by acozine** [comment]
Port 8000 is now open to the VPN. Since the `Fetch fresh monitoring data from host` task is connecting to `server_url: "{{ checkmk_agent_server_protocol }}://{{ checkmk_agent_server }}:{{ checkmk_agent_server_port }}/"`, I tried changing `checkmk_agent_server_port` to `8000` to see if it would connect to the Receiver. It seems that same port is used by an earlier task, which then fails:
```
TASK [checkmk.general.agent : Linux: Download Vanilla CRE agent.] *****************************************
FAILED - RETRYING: [pdc-describe-staging1.princeton.edu]: Linux: Download Vanilla CRE agent. (3 retries left).
FAILED - RETRYING: [pdc-describe-staging1.princeton.edu]: Linux: Download Vanilla CRE agent. (2 retries left).
FAILED - RETRYING: [pdc-describe-staging1.princeton.edu]: Linux: Download Vanilla CRE agent. (1 retries left).
fatal: [pdc-describe-staging1.princeton.edu]: FAILED! => {"attempts": 3, "changed": false, "dest": "/tmp/check-mk-agent_2.2.0p9-vanilla.deb", "elapsed": 0, "gid": 0, "group": "root", "mode": "0640", "msg": "Request failed: <urlopen error [Errno 111] Connection refused>", "owner": "root", "size": 4016434, "state": "file", "uid": 0, "url": "https://pulcheck-staging.princeton.edu:8000/pulmonitor/check_mk/agents/check-mk-agent_2.2.0p9-1_all.deb"}
```
I tried to set separate ports for the two tasks, by copying the `agent` role into our repo (on the branch) so I could modify it and changing the variable in the `Fetch fresh monitoring data from host` task to be `checkmk_agent_receiver_port`,. I set our playbook to run the local copy of the role, and set the two port variables separately:
```
    - checkmk_agent_server_port: 443
    - checkmk_agent_receiver_port: 8000
```
The `Download Vanilla CRE agent` task went back to passing, but the `Fetch fresh monitoring data` task still failed, though it returned a different error:
```
TASK [../../roles/checkmk_agent : Fetch fresh monitoring data from host.] *********************************
FAILED - RETRYING: [pdc-describe-staging1.princeton.edu -> localhost]: Fetch fresh monitoring data from host. (3 retries left).
FAILED - RETRYING: [pdc-describe-staging1.princeton.edu -> localhost]: Fetch fresh monitoring data from host. (2 retries left).
FAILED - RETRYING: [pdc-describe-staging1.princeton.edu -> localhost]: Fetch fresh monitoring data from host. (1 retries left).
fatal: [pdc-describe-staging1.princeton.edu -> localhost]: FAILED! => {"attempts": 3, "changed": false, "msg": "-1 - Error calling API Details: Request failed: <urlopen error timed out>"}
```
I also tried setting `checkmk_agent_tls: 'true'`, which made a different task fail:
```
TASK [checkmk.general.agent : Linux: Register Agent for TLS.] *********************************************
fatal: [pdc-describe-staging1.princeton.edu]: FAILED! => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": true}
```

**Comment by acozine** [comment]
As of 0c700761bc0ba43b4a04b85a146e5e7260eddf7e the playbook successfully installs the agent and creates a host record on the checkMK server. It still fails on the `Fetch fresh monitoring data from host` task, but we get a new error:
```
fatal: [ansible-tower2.princeton.edu -> localhost]: FAILED! => {"attempts": 3, "changed": false, "msg": "-1 - Error calling API Details: Connection failure: Remote end closed connection without response"}
```
Ansible seems to be delegating this task to `localhost` . . . maybe that is related to the failure?

**Comment by acozine** [comment]
As of Feb. 23, the playbook worked. Final steps for this project:
- [ ] find a solution for tracking the `checkmk_folder` across our inventory
- [ ] do we want a default value for `checkmk_folder` - something like `undefined` or `newly added`, so if we add a host that does not have this var defined, the playbook will still run?
- [ ] coordinate with the PR to automate creating the server to make sure we're using the same automation user and password
- [ ] remove the local copy of the agent role, since we can use the generic role straight off galaxy
- [ ] do we want to move the checkMK variables into `group_vars`?

**Comment by acozine** [comment]
The playbook runs by default on every machine in our inventory (on `staging:qa:production`). Best practice is to use `--limit` with a machine or group. If you know the folder you want the machine/group to end up in, add an extra var (all lower case) for now - eventually we may store that information in group vars. Folders are relative to the `Main` folder - for example `linux/dls`. 

To run the playbook: 
`ansible-playbook playbooks/utils/checkmk_agent.yml --limit=<machine/group> -e checkmk_folder=linux/rdss`

**Review by carolyncole — APPROVED** [review]
Awesome! It is running well!

**Pull request merged**
