### PR TITLE
Adding http configuration for library-prod

### PR DESCRIPTION
**Pull request by carolyncole**

### CODE REVIEW

**Comment by kayiwa** [comment]
the restriction to campus IP's is temporary yes?

**Comment by carolyncole** [comment]
@kayiwa the file is complete copy from staging.  So yes we will need to remove that, but not until we are ready to move it to online.

**Comment by kayiwa** [comment]
The certs are in @carolyncole

**Comment by kayiwa** [comment]
hey @kevinreiss since both @carolyncole and I worked on this. Mind reviewing and merging please?

**Comment by kevinreiss** [comment]
👍

**Pull request merged**
