### PR TITLE
Add playbook to install rapid7

### PR DESCRIPTION
**Pull request by acozine**
Per OIT policy, we are starting to install Rapid7 InsightVM on our machines. This PR adds:
- a playbook
- a vaulted token for authorization
- the install script

Right now we are only adding this utility on staging machines.

### CODE REVIEW

**Comment by acozine** [comment]
CI has been failing on this branch with:
```
 TASK [cantaloupe : Install Cantaloupe] *****************************************
  fatal: [instance]: FAILED! => {"changed": false, "msg": "Failure downloading https://github.com/medusa-project/cantaloupe/releases/download/v4.0.3/Cantaloupe-4.0.3.zip, HTTP Error 503: Egress is over the account limit."}
```
Is this something we should add to our mirror?

**Comment by hackartisan** [comment]
Could we have this PR ref a ticket that explains why / what rapid7 is?

**Comment by acozine** [comment]
Good idea @hackartisan.

We put what we know about Rapid7 into a file in pul-it-handbook. I don't think that PR has been merged yet - it's https://github.com/pulibrary/pul-it-handbook/pull/138

**Review by kayiwa — APPROVED** [review]
Thank you! OK!

**Pull request merged**
