### PR TITLE
Use more generalized variable name for unwanted versions of PHP, ensure they are uninstalled

### LINKED ISSUE #3489: Ensure unwanted PHP versions are uninstalled
See https://github.com/pulibrary/princeton_ansible/issues/3486 for some context. 

When downgrading PHP versions (e.g. from 8.1 to 8.0), the application is still looking at the newest version of PHP even after running the playbook. Once the playbook is run, the application should point to the version of PHP in the variables.

### PR DESCRIPTION
**Pull request by maxkadel**
Use a wildcard rather than list of packages.

Closes #3489

### CODE REVIEW

**Comment by acozine** [comment]
Current failure is:
```
   TASK [php : php | remove packages that begin with 'php7.4'] ********************
  fatal: [instance]: FAILED! => {"changed": false, "msg": "No package(s) matching 'php7.4*' available"}
```

**Comment by maxkadel** [comment]
> Current failure is:
> 
> ```
>    TASK [php : php | remove packages that begin with 'php7.4'] ********************
>   fatal: [instance]: FAILED! => {"changed": false, "msg": "No package(s) matching 'php7.4*' available"}
> ```

I'm trying to look at this and I'm confused - if there are no packages on the machine that match `php7.4*`, then shouldn't ansible just respond "ok", since the state of the machine is what we want? I feel like there's something I'm not understanding about this. 

Trying adding `fail_on_autoremove: false`, even though that's supposed to be the default

**Comment by maxkadel** [comment]
Still has the same problem - 

```
 TASK [php : php | remove packages that begin with 'php7.4'] ********************
 fatal: [instance]: FAILED! => {"changed": false, "msg": "No package(s) matching 'php7.4*' available"}
```

**Comment by maxkadel** [comment]
May be related to this issue - https://github.com/ansible/ansible/issues/62262

**Comment by acozine** [comment]
Nice sleuthing @maxkadel! This is an excellent step forward.

**Pull request merged**
