### PR TITLE
Ensures that redis can be installed on Ubuntu 18.04 by enabling IPv6

### LINKED ISSUE #406: pulibrary.redis Role fails for Ubuntu 18.04 LTS environments
Currently the following errors are logged during the installation:

```
Setting up redis-server (5:4.0.9-1ubuntu0.1) ...
Job for redis-server.service failed because a timeout was exceeded
```

### PR DESCRIPTION
**Pull request by jrgriffiniii**
Resolves #406

### CODE REVIEW

**Comment by kayiwa** [comment]
this is a strange one @jrgriffiniii I think it will be OK but IPv6 is disabled because it is "considered bad network citizenship" on princeton's network.

**Comment by kayiwa** [comment]
See here. https://github.com/pulibrary/vmimages/blob/5fec27b8c65cf31c2a4d8f7dee86cc683dc0461c/ansible/roles/lockdown/tasks/main.yml#L45

**Comment by jrgriffiniii** [comment]
https://github.com/pulibrary/vmimages/pull/31 resolves this, but if this becomes a security concern over IPv6 usage, then perhaps another solution should be offered.

**Comment by bearnxx** [comment]
@jrgriffiniii  how to  resolve the problem ?  the link is all 404 at this page.

**Pull request closed without merging**
