### PR TITLE
Remove lib elixir

### PR DESCRIPTION
**Pull request by acozine**
Related to #2578.

Since we are not using the lib-elixir site, we did not renew the SSL certificate for it. However, the site is still configured on the load-balancer. This PR would decommission the site entirely:

- [ ] removes the site config from the load balancer
- [ ] removes the VM from the hosts file

This PR should remain a draft until the full DLS team can review.

### CODE REVIEW

**Review by hackartisan — CHANGES_REQUESTED** [review]
I think we could also remove the playbook and the associated group_vars files: https://github.com/pulibrary/princeton_ansible/blob/main/playbooks/elixir_test.yml

Also the elixir role.

Block pending confirmation of all this with DLS team.

**Comment by acozine** [comment]
Confirmed at standup today: this project, including the VM, the role, and the website, is now decommissioned and all trace of it can be removed.

**Review by hackartisan — APPROVED** [review]
🎉

**Comment by acozine** [comment]
Ran the playbook today and the lib-elixir.princeton.edu site is gone from the load balancer, though it lives on in the cache of one of my browsers.

**Comment by acozine** [comment]
Also needed to decommission the IPs, remove alias (via OIT), and remove associated firewall rules. Taking care of those today.

**Pull request merged**
