### PR TITLE
Delete mariadb roles

### LINKED ISSUE #1850: delete mariadbserver server role
Once matomo has been shut down we can delete this role.  Do not bother upgrading it to molecule 3

### PR DESCRIPTION
**Pull request by acozine**
Closes #1850.

The first four commits remove the mariadb roles from our ansible ecosystem. However, there are still a lot of variables, passwords, and other mentions of mariadb in various places in the repo. Should/can those also be removed?

### CODE REVIEW

**Comment by acozine** [comment]
I'm curious about some of these other roles - with mariadb gone, some of them look like they no longer have any database connections at all, which seems a bit odd.

**Comment by kevinreiss** [comment]
We have a number of applications with playbooks that still actively use mariadb.

**Comment by acozine** [comment]
Oh, good to know. I was going off of https://github.com/pulibrary/princeton_ansible/issues/1850. Which projects still use mariadb?

**Comment by kevinreiss** [comment]
libwww_production, libwww_staging, locator_production, locator_staging, pas_production, pas_staging, special_collections_prod, special_collections_staging, friends_of_pul_prod, friends_of_pul_staging. recap_production, recap_staging are the roles that cover application using mariadb.

**Comment by carolyncole** [comment]
mariadbserver and mariadb are two different roles.  mariadb is still in use.

**Review by carolyncole — CHANGES_REQUESTED** [review]
Please remove any references to removing mariadb

**Comment by carolyncole** [comment]
This was the role I was referencing https://github.com/pulibrary/princeton_ansible/tree/main/roles/mariadbserver

**Comment by acozine** [comment]
Thanks @kevinreiss @carolyncole! I'm closing this PR in favor of #2684. That PR only removes mariadbserver (and fixes the CI errors I ran into). I'll use the comments here as a start on my list-of-databases-we-use.

**Pull request closed without merging**
